# Generated by Django 3.2 on 2023-10-16 21:19

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buyers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=150, verbose_name='Фмилия')),
                ('emailad', models.EmailField(max_length=254, verbose_name='поочта')),
                ('numbersTel', models.CharField(max_length=10, unique=True, verbose_name='Телефон')),
                ('shopping_cart', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, size=None, verbose_name='корзина покупателя')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'ordering': ['first_name'],
            },
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categor_name', models.CharField(max_length=150, verbose_name='Наименование категории')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['categor_name'],
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_name', models.CharField(max_length=150, verbose_name='Наименование товара')),
                ('shop_price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена товара')),
                ('opisanie', models.TextField(null=True, verbose_name='Описание товара')),
                ('count_goods', models.IntegerField(default=0, verbose_name='Количество товара')),
                ('available', models.BooleanField(default=True, verbose_name='Доступен')),
                ('image1', models.ImageField(upload_to=main.models.get_path_save1, verbose_name='Фото товара 1')),
                ('image2', models.ImageField(upload_to=main.models.get_path_save1, verbose_name='Фото товара 2')),
                ('image3', models.ImageField(upload_to=main.models.get_path_save1, verbose_name='Фото товара 3')),
                ('image4', models.ImageField(upload_to=main.models.get_path_save1, verbose_name='Фото товара 4')),
                ('image5', models.ImageField(upload_to=main.models.get_path_save1, verbose_name='Фото товара 5')),
                ('image6', models.ImageField(upload_to=main.models.get_path_save1, verbose_name='Фото товара 6')),
                ('image7', models.ImageField(upload_to=main.models.get_path_save1, verbose_name='Фото товара 7')),
                ('image8', models.ImageField(upload_to=main.models.get_path_save1, verbose_name='Фото товара 8')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['goods_name'],
            },
        ),
        migrations.CreateModel(
            name='Makers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameMaker', models.CharField(max_length=150, verbose_name='Наименование производителя')),
                ('countryMaker', models.CharField(max_length=150, verbose_name='Наименование производителя')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyGoods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameProperty', models.CharField(max_length=150, verbose_name='Наименование свойства')),
                ('unitProperty', models.CharField(max_length=150, verbose_name='Еденица измерения')),
                ('quantyProperty', models.IntegerField(default=0, verbose_name='Количество')),
                ('boolProperty', models.BooleanField(default=False, verbose_name='Свойство Да/Нет')),
                ('boolValueProperty', models.BooleanField(default=False, verbose_name='Значение Да/Нет')),
            ],
            options={
                'verbose_name': 'Свойство',
                'verbose_name_plural': 'Свойства товаров и их значения',
                'ordering': ['nameProperty'],
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_numb', models.CharField(max_length=50, unique=True, verbose_name='Номер заказа')),
                ('order_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата заказа')),
                ('status_order', models.CharField(max_length=50, verbose_name='Статус заказа')),
                ('price_good', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена товара')),
                ('goods_order', models.ManyToManyField(to='main.Goods', verbose_name='Товары')),
                ('orders_buy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.buyers', verbose_name='покупатель')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['order_date'],
            },
        ),
        migrations.AddField(
            model_name='goods',
            name='brend',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.makers'),
        ),
        migrations.AddField(
            model_name='goods',
            name='categor_goods',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.categories'),
        ),
        migrations.AddField(
            model_name='goods',
            name='property_name',
            field=models.ManyToManyField(to='main.PropertyGoods', verbose_name='Свойства товара'),
        ),
    ]
