# Generated by Django 3.2 on 2023-10-16 21:35

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='makers',
            options={'ordering': ['nameMaker'], 'verbose_name': 'производитель', 'verbose_name_plural': 'Производители'},
        ),
        migrations.AlterField(
            model_name='goods',
            name='image2',
            field=models.ImageField(blank=True, upload_to=main.models.get_path_save1, verbose_name='Фото товара 2'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='image3',
            field=models.ImageField(blank=True, upload_to=main.models.get_path_save1, verbose_name='Фото товара 3'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='image4',
            field=models.ImageField(blank=True, upload_to=main.models.get_path_save1, verbose_name='Фото товара 4'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='image5',
            field=models.ImageField(blank=True, upload_to=main.models.get_path_save1, verbose_name='Фото товара 5'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='image6',
            field=models.ImageField(blank=True, upload_to=main.models.get_path_save1, verbose_name='Фото товара 6'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='image7',
            field=models.ImageField(blank=True, upload_to=main.models.get_path_save1, verbose_name='Фото товара 7'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='image8',
            field=models.ImageField(blank=True, upload_to=main.models.get_path_save1, verbose_name='Фото товара 8'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='property_name',
            field=models.ManyToManyField(blank=True, to='main.PropertyGoods', verbose_name='Свойства товара'),
        ),
        migrations.AlterField(
            model_name='makers',
            name='countryMaker',
            field=models.CharField(max_length=150, verbose_name='Страна производителя'),
        ),
    ]
